name: root
channels:
- conda-forge
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.5.1=py35_0
- bokeh=0.12.3=py35_1
- bzip2=1.0.6=vc14_3
- clyent=1.2.2=py35_0
- colorama=0.3.7=py35_0
- conda-forge::boto3=1.4.1=py35_0
- conda-forge::botocore=1.4.49=py35_0
- conda-forge::bottleneck=1.2.0=np111py35_0
- conda-forge::click=6.6=py35_1
- conda-forge::cloudpickle=0.2.1=py35_2
- conda-forge::conda=4.1.12=py35_0
- conda-forge::conda-env=2.5.2=py35_0
- conda-forge::curl=7.49.1=vc14_1
- conda-forge::cyordereddict=1.0.0=py35_1
- conda-forge::dask=0.12.0=py35_0
- conda-forge::distributed=1.14.1=py35_0
- conda-forge::docutils=0.12=py35_0
- conda-forge::future=0.15.2=py35_0
- conda-forge::h5netcdf=0.3.1=py35_0
- conda-forge::h5py=2.6.0=np111py35_6
- conda-forge::hdf5=1.8.17=vc14_6
- conda-forge::heapdict=1.0.0=py35_0
- conda-forge::jmespath=0.9.0=py35_0
- conda-forge::libiconv=1.14=vc14_3
- conda-forge::libnetcdf=4.4.0=vc14_2
- conda-forge::libxml2=2.9.4=vc14_1
- conda-forge::libxslt=1.1.29=vc14_1
- conda-forge::locket=0.2.0=py35_0
- conda-forge::lxml=3.6.4=py35_0
- conda-forge::msgpack-python=0.4.8=py35_0
- conda-forge::netcdf4=1.2.4=np111py35_2
- conda-forge::obspy=1.0.2=py35_1
- conda-forge::pandas=0.19.0=np111py35_0
- conda-forge::partd=0.3.6=py35_0
- conda-forge::patsy=0.4.1=py35_0
- conda-forge::psutil=4.3.0=py35_0
- conda-forge::s3fs=0.0.7=py35_0
- conda-forge::s3transfer=0.1.8=py35_0
- conda-forge::seaborn=0.7.1=py35_0
- conda-forge::statsmodels=0.6.1=np111py35_0
- conda-forge::toolz=0.8.0=py35_0
- conda-forge::vc=14=0
- conda-forge::xarray=0.8.2=py35_0
- conda-forge::zict=0.1.0=py35_0
- console_shortcut=0.1.1=py35_1
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- freetype=2.5.5=vc14_1
- hdf4=4.2.12=vc14_0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jinja2=2.8=py35_1
- jpeg=8d=vc14_2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- libpng=1.6.22=vc14_0
- libtiff=4.0.6=vc14_2
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np111py35_0
- menuinst=1.4.1=py35_0
- mistune=0.7.3=py35_0
- mkl=11.3.3=1
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- networkx=1.11=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.1=py35_1
- openssl=1.0.2i=vc14_0
- path.py=8.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.3.1=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- pycosat=0.6.1=py35_1
- pycrypto=2.6.1=py35_4
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_7
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyyaml=3.11=py35_4
- pyzmq=15.4.0=py35_0
- qt=4.8.7=vc14_9
- qtconsole=4.2.1=py35_0
- requests=2.10.0=py35_0
- ruamel_yaml=0.11.14=py35_0
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.17.1=np111py35_1
- scipy=0.18.1=np111py35_0
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlalchemy=1.0.13=py35_0
- tblib=1.3.0=py35_0
- tk=8.5.18=vc14_0
- tornado=4.4.1=py35_0
- traitlets=4.3.0=py35_0
- vs2015_runtime=14.0.25123=0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- win_unicode_console=0.5=py35_0
- zlib=1.2.8=vc14_3
- pip:
  - boto3==1.4.1
  - botocore==1.4.49
  - bottleneck==1.2.0
  - bruges==0.2.1
  - click==6.6
  - cloudpickle==0.2.1
  - conda==4.1.12
  - conda-env==2.5.0a0
  - cyordereddict==1.0.0
  - dask==0.12.0
  - distributed==1.14.1
  - docutils==0.12
  - future==0.15.2
  - h5netcdf==0.3.1
  - h5py==2.6.0
  - heapdict==1.0.0
  - ipython-genutils==0.1.0
  - jmespath==0.9.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - locket==0.2.0
  - lxml==3.6.4
  - msgpack-python==0.4.8
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - netcdf4==1.2.4
  - obspy==1.0.2
  - pandas==0.19.0
  - partd==0.3.6
  - patsy==0.4.1
  - prompt-toolkit==1.0.3
  - psutil==4.3.0
  - ruamel-yaml-==VERSION
  - s3fs==0.0.7
  - s3transfer==0.1.8
  - seaborn==0.7.1
  - segpy==2.0.0a2
  - statsmodels==0.6.1
  - toolz==0.8.0
  - win-unicode-console==0.5
  - xarray==0.8.2
  - zict==0.1.0
